export const ADD_ITEMS_TO_CONSTRUCTOR = 'ADD_ITEMS_TO_CONSTRUCTOR';
export const REMOVE_ITEMS_IN_CONSTRUCTOR = 'REMOVE_ITEMS_IN_CONSTRUCTOR';
export const CALCULATE_PRICE = "CALCULATE_PRICE"

export const OPEN_ORDER_MODAL = "OPEN_ORDER_MODAL"
export const CLOSE_ORDER_MODAL = "CLOSE_ORDER_MODAL"


export const ADD_ORDER = "ADD_ORDER"