export const NAVIGATE_TO = 'NAVIGATE_TO'

export const RESET_PASS_REQUEST = 'RESET_PASS_REQUEST'

export const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS'

export const RESET_PASS_FAILED = 'RESET_PASS_FAILED'

