export const WS_CONNECTION_START = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE = 'WS_GET_MESSAGE';


export const WS_USER_CONNECTION_START = 'WS_USER_CONNECTION_START';
export const WS_USER_CONNECTION_SUCCESS = 'WS_USER_CONNECTION_SUCCESS';
export const WS_USER_CONNECTION_ERROR = 'WS_USER_CONNECTION_ERROR';
export const WS_USER_CONNECTION_CLOSED = 'WS_USER_CONNECTION_CLOSED';
export const WS_USER_GET_MESSAGE = 'WS_USER_GET_MESSAGE';
export const OPEN_USER_ORDERS_MODAL = 'OPEN_USER_ORDERS_MODAL';
export const CLOSE_USER_ORDERS_MODAL = 'CLOSE_USER_ORDERS_MODAL';
export const OPEN_ORDERS_MODAL = 'OPEN_ORDERS_MODAL';
export const CLOSE_ORDERS_MODAL = 'CLOSE_ORDERS_MODAL';
